<?php

$lang = array_merge($lang, array(
'Accueil'	=>	'Accueil',
'Actif'	=>	'Actif',
'Administration'	=>	'Administration',
'Adresse'	=>	'Adresse',
'Ajouter'	=>	'Ajouter',
'Code_postal'	=>	'Code postal',
'Configuration_ok'	=>	'Aucun probleme de configuration dans la base',
'Confirm_suppression_site'	=>	'Etes vous sur de vouloir supprimer le site',
'Contacts'	=>	'Contacts',
'Description'	=>	'Description',
'Edition_site'	=>	'Edition site',
'Email'	=>	'Email',
'Enregistrer'	=>	'Enregistrer',
'Fax'	=>	'Fax',
'Nom_du_site'	=>	'Nom du site',
'Non'	=>	'Non',
'Nouveau_site'	=>	'Nouveau site',
'Nouveau_site_enregistre'	=>	'Nouveau site enregistré',
'Maintenance'	=>	'Maintenance',
'Modifier'	=>	'Modifier',
'Module'	=>	'Module',
'Modules'	=>	'Modules',
'Lieux'	=>	'Lieux',
'Logo'	=>	'Logo',
'Oui'	=>	'Oui',
'Recherche_multiple_par_code_ape'	=>	'Recherche par plusieurs code APE',
'Siege'	=>	'Siège',
'Site'	=>	'Site',
'Sites'	=>	'Sites',
'Supprimer'	=>	'Supprimer',
'Telephone'	=>	'Téléphone',
'Verification_configuration'	=>	'Verification de la configuration',
'Verifier'	=>	'Vérifier',
'Ville'	=>	'Ville',
));